fix rollingUpdate
Signed-off-by: jooho lee <jlee@redhat.com>

diff --git a/config/runtimes/vllm-multinode-template.yaml b/config/runtimes/vllm-multinode-template.yaml
--- a/config/runtimes/vllm-multinode-template.yaml
+++ b/config/runtimes/vllm-multinode-template.yaml
@@ -39,18 +39,18 @@ objects:
           command: [ "bash", "-c" ]
           args:
             - |
-              ray start --head --disable-usage-stats --include-dashboard false 
-              # wait for other node to join
-              until [[ $(ray status --address ${RAY_ADDRESS} | grep -c node_) -eq ${PIPELINE_PARALLEL_SIZE} ]]; do
-                echo "Waiting..."
-                sleep 1
-              done
-              ray status --address ${RAY_ADDRESS}
+                ray start --head --disable-usage-stats --include-dashboard false 
+                # wait for other node to join
+                until [[ $(ray status --address ${RAY_ADDRESS} | grep -c node_) -ge ${PIPELINE_PARALLEL_SIZE} ]]; do
+                  echo "Waiting..."
+                  sleep 1
+                done
+                ray status --address ${RAY_ADDRESS}
 
-              export SERVED_MODEL_NAME=${MODEL_NAME}
-              export MODEL_NAME=${MODEL_DIR} 
-              
-              exec python3 -m vllm.entrypoints.openai.api_server --port=8080 --distributed-executor-backend ray --model=${MODEL_NAME} --served-model-name=${SERVED_MODEL_NAME} --tensor-parallel-size=${TENSOR_PARALLEL_SIZE} --pipeline-parallel-size=${PIPELINE_PARALLEL_SIZE} --disable_custom_all_reduce
+                export SERVED_MODEL_NAME=${MODEL_NAME}
+                export MODEL_NAME=${MODEL_DIR} 
+                
+                exec python3 -m vllm.entrypoints.openai.api_server --port=8080 --distributed-executor-backend ray --model=${MODEL_NAME} --served-model-name=${SERVED_MODEL_NAME} --tensor-parallel-size=${TENSOR_PARALLEL_SIZE} --pipeline-parallel-size=${PIPELINE_PARALLEL_SIZE} --disable_custom_all_reduce
           env:
             - name: RAY_PORT
               value: "6379"
@@ -85,22 +85,20 @@ objects:
               command:
                 - bash
                 - -c
-                - |
-                  # Check if the registered ray nodes count is the same as PIPELINE_PARALLEL_SIZE
-                  gpu_status=$(ray status --address ${RAY_ADDRESS} | grep GPU)
-                  if [[ -z ${gpu_status} ]]; then
-                    echo "Unhealthy - GPU does not exist"
-                    exit 1
-                  fi
+                - |                  
+                    # Check if the registered ray nodes count is greater or the same than PIPELINE_PARALLEL_SIZE
+                    registered_node_count=$(ray status --address ${RAY_ADDRESS} | grep -c node_)
+                    if [[ ! ${registered_node_count} -ge "${PIPELINE_PARALLEL_SIZE}" ]]; then
+                      echo "Unhealthy - Registered nodes count (${registered_node_count}) does not match PIPELINE_PARALLEL_SIZE (${PIPELINE_PARALLEL_SIZE})."
+                      exit 1
+                    fi     
 
-                  used_gpu=$(echo "${gpu_status}" | awk '{print $1}' | cut -d'/' -f1)
-                  reserved_gpu=$(echo "${gpu_status}" | awk '{print $1}' | cut -d'/' -f2)
-
-                  # Determine health status based on GPU usage
-                  if [[ "${used_gpu}" != "${reserved_gpu}" ]]; then
-                    echo "Unhealthy - Used: ${used_gpu}, Reserved: ${reserved_gpu}"
-                    exit 1
-                  fi
+                    # Check model health
+                    health_check=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8080/health)
+                    if [[ ${health_check} != 200 ]]; then
+                      echo "Unhealthy - vLLM Runtime Health Check failed." 
+                      exit 1
+                    fi                  
           readinessProbe:
             failureThreshold: 2
             periodSeconds: 5
@@ -110,36 +108,13 @@ objects:
               command:
                 - bash
                 - -c
-                - |
-                  # Check if the registered nodes count matches PIPELINE_PARALLEL_SIZE
-                  registered_node_count=$(ray status --address ${RAY_ADDRESS} | grep -c node_)
-                  if [[ ${registered_node_count} -ne "${PIPELINE_PARALLEL_SIZE}" ]]; then
-                    echo "Unhealthy - Registered nodes count (${registered_node_count}) does not match PIPELINE_PARALLEL_SIZE (${PIPELINE_PARALLEL_SIZE})."
-                    exit 1
-                  fi
-
-                  # Check if the registered ray nodes count is the same as PIPELINE_PARALLEL_SIZE
-                  gpu_status=$(ray status --address ${RAY_ADDRESS} | grep GPU)
-                  if [[ -z ${gpu_status} ]]; then
-                    echo "Unhealthy - GPU does not exist"
-                    exit 1
-                  fi
-
-                  used_gpu=$(echo "${gpu_status}" | awk '{print $1}' | cut -d'/' -f1)
-                  reserved_gpu=$(echo "${gpu_status}" | awk '{print $1}' | cut -d'/' -f2)
-
-                  # Determine health status based on GPU usage
-                  if [[ "${used_gpu}" != "${reserved_gpu}" ]]; then
-                    echo "Unhealthy - Used: ${used_gpu}, Reserved: ${reserved_gpu}"
-                    exit 1
-                  fi
-                  
-                  # Check model health 
-                  health_check=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8080/health)
-                  if [[ ${health_check} != 200 ]]; then
-                    echo "Unhealthy - vLLM Runtime Health Check failed." 
-                    exit 1
-                  fi
+                - |                    
+                    # Check model health 
+                    health_check=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8080/health)
+                    if [[ ${health_check} != 200 ]]; then
+                      echo "Unhealthy - vLLM Runtime Health Check failed." 
+                      exit 1
+                    fi
           startupProbe:
             failureThreshold: 40
             periodSeconds: 30
@@ -150,24 +125,31 @@ objects:
               command:
                 - bash
                 - -c
-                - |
-                  # This need when head node have issues and restarted.
-                  # It will wait for new worker node.                     
-                  registered_node_count=$(ray status --address ${RAY_ADDRESS} | grep -c node_)
-                  if [[ ${registered_node_count} -ne "${PIPELINE_PARALLEL_SIZE}" ]]; then
-                    echo "Unhealthy - Registered nodes count (${registered_node_count}) does not match PIPELINE_PARALLEL_SIZE (${PIPELINE_PARALLEL_SIZE})."
-                    exit 1
-                  fi
-                  
-                  # Double check to make sure Model is ready to serve.
-                  for i in 1 2; do                    
-                    # Check model health
-                    health_check=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8080/health)
-                    if [[ ${health_check} != 200 ]]; then
-                      echo "Unhealthy - vLLM Runtime Health Check failed." 
+                - |                
+                    # Check if there is GPU resource
+                    gpu_status=$(ray status --address ${RAY_ADDRESS} | grep GPU)
+                    if [[ -z ${gpu_status} ]]; then
+                      echo "Unhealthy - GPU does not exist"
                       exit 1
                     fi
-                  done
+
+                    # Check if the registered ray nodes count is greater or the same than PIPELINE_PARALLEL_SIZE
+                    # This need when head node have issues and restarted. It will wait for new worker node.                     
+                    registered_node_count=$(ray status --address ${RAY_ADDRESS} | grep -c node_)
+                    if [[ ! ${registered_node_count} -ge "${PIPELINE_PARALLEL_SIZE}" ]]; then
+                      echo "Unhealthy - Registered nodes count (${registered_node_count}) does not match PIPELINE_PARALLEL_SIZE (${PIPELINE_PARALLEL_SIZE})."
+                      exit 1
+                    fi
+                  
+                    # Double check to make sure Model is ready to serve.
+                    for i in 1 2; do                    
+                      # Check model health
+                      health_check=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8080/health)
+                      if [[ ${health_check} != 200 ]]; then
+                        echo "Unhealthy - vLLM Runtime Health Check failed." 
+                        exit 1
+                      fi
+                    done
           ports:
             - containerPort: 8080
               name: http
@@ -186,30 +168,29 @@ objects:
             command: [ "bash", "-c" ]
             args:
               - |
-                SECONDS=0
+                  SECONDS=0
 
-                while true; do              
-                  if (( SECONDS <= 240 )); then
-                    if ray health-check --address "${HEAD_SVC}.${POD_NAMESPACE}.svc.cluster.local:6379" > /dev/null 2>&1; then
-                      echo "Global Control Service(GCS) is ready."
-                      break
+                  while true; do              
+                    if (( SECONDS <= 240 )); then
+                      if ray health-check --address "${HEAD_SVC}.${POD_NAMESPACE}.svc.cluster.local:6379" > /dev/null 2>&1; then
+                        echo "Ray Global Control Service(GCS) is ready."
+                        break
+                      fi
+                      echo "$SECONDS seconds elapsed: Waiting for Ray Global Control Service(GCS) to be ready."
+                    else
+                      if ray health-check --address "${HEAD_SVC}.${POD_NAMESPACE}.svc.cluster.local:6379"; then
+                        echo "Ray Global Control Service(GCS) is ready. Any error messages above can be safely ignored."
+                        break
+                      fi
+                      echo "$SECONDS seconds elapsed: Still waiting for Ray Global Control Service(GCS) to be ready."
                     fi
-                    echo "$SECONDS seconds elapsed: Waiting for Global Control Service(GCS) to be ready."
-                  else
-                    if ray health-check --address "${HEAD_SVC}.${POD_NAMESPACE}.svc.cluster.local:6379"; then
-                      echo "Global Control Service(GCS) is ready. Any error messages above can be safely ignored."
-                      break
-                    fi
-                    echo "$SECONDS seconds elapsed: Still waiting for Global Control Service(GCS) to be ready."
-                    echo "For troubleshooting, refer to the FAQ at https://docs.ray.io/en/master/cluster/kubernetes/troubleshooting/troubleshooting.html#kuberay-troubleshootin-guides"
-                  fi
-                
-                  sleep 5
-                done
+                  
+                    sleep 5
+                  done
 
-                export RAY_HEAD_ADDRESS="${HEAD_SVC}.${POD_NAMESPACE}.svc.cluster.local:6379"
-                echo "Attempting to connect to Ray cluster at $RAY_HEAD_ADDRESS ..."
-                ray start --address="${RAY_HEAD_ADDRESS}" --block
+                  export RAY_HEAD_ADDRESS="${HEAD_SVC}.${POD_NAMESPACE}.svc.cluster.local:6379"
+                  echo "Attempting to connect to Ray cluster at $RAY_HEAD_ADDRESS ..."
+                  ray start --address="${RAY_HEAD_ADDRESS}" --block
             env:
               - name: POD_NAME
                 valueFrom:
@@ -219,7 +200,7 @@ objects:
                 valueFrom:
                   fieldRef:
                     fieldPath: metadata.namespace
-            resources:
+            resourcesvllm-llama3-8b-predictor-worker:
               limits:
                 cpu: "16"
                 memory: 48Gi
@@ -239,12 +220,12 @@ objects:
                   - bash
                   - -c
                   - |
-                    # Check if the registered nodes count matches PIPELINE_PARALLEL_SIZE
-                    registered_node_count=$(ray status --address ${HEAD_SVC}.${POD_NAMESPACE}.svc.cluster.local:6379 | grep -c node_)
-                    if [[ ${registered_node_count} -ne "${PIPELINE_PARALLEL_SIZE}" ]]; then
-                      echo "Unhealthy - Registered nodes count (${registered_node_count}) does not match PIPELINE_PARALLEL_SIZE (${PIPELINE_PARALLEL_SIZE})."
-                      exit 1
-                    fi 
+                      # Check if the registered ray nodes count is greater or the same than PIPELINE_PARALLEL_SIZE
+                      registered_node_count=$(ray status --address ${HEAD_SVC}.${POD_NAMESPACE}.svc.cluster.local:6379 | grep -c node_)
+                      if [[ ! ${registered_node_count} -ge "${PIPELINE_PARALLEL_SIZE}" ]]; then
+                        echo "Unhealthy - Registered nodes count (${registered_node_count}) does not match PIPELINE_PARALLEL_SIZE (${PIPELINE_PARALLEL_SIZE})."
+                        exit 1
+                      fi                   
             startupProbe:
               failureThreshold: 40
               periodSeconds: 30
@@ -255,23 +236,24 @@ objects:
                 command:
                   - /bin/sh
                   - -c
-                  - |
-                    registered_node_count=$(ray status --address ${HEAD_SVC}.${POD_NAMESPACE}.svc.cluster.local:6379 | grep -c node_)
-                    if [[ ${registered_node_count} -ne "${PIPELINE_PARALLEL_SIZE}" ]]; then
-                      echo "Unhealthy - Registered nodes count (${registered_node_count}) does not match PIPELINE_PARALLEL_SIZE (${PIPELINE_PARALLEL_SIZE})."
-                      exit 1
-                    fi  
-                    
-                    # Double check to make sure Model is ready to serve.
-                    for i in 1 2; do
-                      # Check model health
-                      model_health_check=$(curl -s ${HEAD_SVC}.${POD_NAMESPACE}.svc.cluster.local:8080/v1/models|grep -o ${ISVC_NAME})
-                      if [[ ${model_health_check} != "${ISVC_NAME}" ]]; then
-                        echo "Unhealthy - vLLM Runtime Health Check failed."
+                  - |                                            
+                      # Check if the registered ray nodes count is greater or the same than PIPELINE_PARALLEL_SIZE
+                      registered_node_count=$(ray status --address ${HEAD_SVC}.${POD_NAMESPACE}.svc.cluster.local:6379 | grep -c node_)
+                      if [[ ! ${registered_node_count} -ge "${PIPELINE_PARALLEL_SIZE}" ]]; then
+                        echo "Unhealthy - Registered nodes count (${registered_node_count}) does not match PIPELINE_PARALLEL_SIZE (${PIPELINE_PARALLEL_SIZE})."
                         exit 1
-                      fi                     
-                      sleep 10
-                    done
+                      fi  
+                      
+                      # Double check to make sure Model is ready to serve.
+                      for i in 1 2; do
+                        # Check model health
+                        model_health_check=$(curl -s ${HEAD_SVC}.${POD_NAMESPACE}.svc.cluster.local:8080/v1/models|grep -o ${ISVC_NAME})
+                        if [[ ${model_health_check} != "${ISVC_NAME}" ]]; then
+                          echo "Unhealthy - vLLM Runtime Health Check failed."
+                          exit 1
+                        fi                     
+                        sleep 10
+                      done
         volumes:
           - name: shm
             emptyDir:
